POST http://localhost:3000/blog
Content-Type: application/json

{
  "title": "Understanding Clean Architecture in Go",
  "content": "This blog post explores the principles of clean architecture and how to apply them in Go applications.",
  "user_id": "64eabc0c6c7f4a76b6c133aa",
  "tags": ["golang", "architecture", "backend"]
}

###
PUT http://localhost:3000/blog/6890c2ddb4cccc6f10214d3c
Content-Type: application/json

{
  "title": "what is go? why is go?",
  "content": "This blog post explores the principles of clean architecture and how to apply them in Go applications.",
  "user_id": "64eabc0c6c7f4a76b6c133aa",
  "tags": ["banana", "apple", "brocolli"]

}

###
GET http://localhost:3000/blog/6899b1e781cc769d421a345c

###
DELETE http://localhost:3000/blog/6899b1e781cc769d421a345c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTUyNTYyMDQsInVzZXJfaWQiOiI2ODkxYWM4NzNhY2U4M2M4NzFjZjRhZWQifQ.NRcS6-CaKegJAkVTMqF99wGe7E29F1eMzgbcar2qIgc

###
GET http://localhost:3000/blog/search
Content-Type: application/json

{
  "title": "what is go? why is go?"
}

###
DELETE http://localhost:8080/users/687e28154e45ffe7f6f7e3a1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTMzNTc2NTgsInVzZXJfaWQiOiI2ODdlMjhkMmRlODAzNWFkMzEzODI3MGMifQ.1CeMYtKE-yxgO8F0IwCJexfQ4Yt67m2NJDq4BuUnLNI


###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "Abee",
  "email": "jomamahsd",
  "password": "ABEBEBESOBELA"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "Abee",
  "password": "ABEBEBESOBELA"
}

###
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "abeltesfa198@gmail.com"
}

###
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "Token": "689b244f1e628a0e111c751e",
  "NewPassword": "abebe"
}

###
POST http://localhost:3000/admin/users/promote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTUyNTYzMTcsInVzZXJfaWQiOiI2ODkxYWM4NzNhY2U4M2M4NzFjZjRhZWQifQ.3CHo1voXKdp0mViGAUVD1m8PnPWqWKtW1Ot1j2EeMaw
Content-Type: application/json

{
  "user_id": "6899a6cf3702a4dc19bced22",
  "new_role": "admin"
}

###
GET http://localhost:3000/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTUyNTYzMTcsInVzZXJfaWQiOiI2ODkxYWM4NzNhY2U4M2M4NzFjZjRhZWQifQ.3CHo1voXKdp0mViGAUVD1m8PnPWqWKtW1Ot1j2EeMaw

###
POST http://localhost:3000/blog/6899b1f081cc769d421a345d/dislike
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTUyNTYzMTcsInVzZXJfaWQiOiI2ODkxYWM4NzNhY2U4M2M4NzFjZjRhZWQifQ.3CHo1voXKdp0mViGAUVD1m8PnPWqWKtW1Ot1j2EeMaw


###
POST http://localhost:3000/blog/filter
Content-Type: application/json

{
  "tags": ["banana"],
  "sort_by": "date"  
}

###
POST http://localhost:3000/blog/suggest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTUyNTYzMTcsInVzZXJfaWQiOiI2ODkxYWM4NzNhY2U4M2M4NzFjZjRhZWQifQ.3CHo1voXKdp0mViGAUVD1m8PnPWqWKtW1Ot1j2EeMaw
Content-Type: application/json

{
  "prompt": "Write a blog introduction about modern web development trends."
}
